### ISSUE TITLE
Subclass doesn't decode parent fields

### ISSUE THREAD

**Issue by mnordine** [eredo/dartson#37] opened 2016-06-21 14:37 UTC
Given the following file:

``` dart
import 'package:dartson/dartson.dart';
import 'dart:convert' show JSON;

@Entity()
class Parent
{
  int id;
}

@Entity()
class Child extends Parent
{
  int blah;

  toString() => 'id: $id, blah: $blah';
}

main()
{
  final map = {
    'id': 0,
    'blah': 1
  };

  Child child = new Dartson.JSON().decode(JSON.encode(map), new Child());
  print(child);
}
```

It prints `id: null, blah: 1`

**Comment by mnordine** [comment] 2016-06-21 14:40
Simplified example:

```dart
import 'package:dartson/dartson.dart';
import 'dart:convert' show JSON;

@Entity()
class Parent
{
  int id;
}

@Entity()
class Child extends Parent
{
  int blah;

  toString() => 'id: $id, blah: $blah';
}

main()
{
  final map = {
    'id': 0,
    'blah': 1
  };

  Child child = new Dartson.JSON().decode(JSON.encode(map), new Child());
  print(child);
}
```

Prints `id: null, blah: 1`

**Comment by seanmccleary** [comment] 2016-11-11 20:18
Is this not a duplicate of #7 ?

**Comment by eredo** [comment] 2018-09-07 16:12
Supported in 1.0.0-alpha

**Closed by eredo** 2018-09-07 16:12 UTC
Labels: bug, confirmed
